In [13]:
import numpy as np
from assortativity import measures as m
from scipy.stats import pearsonr

In [17]:
A = np.array([[0,1,1,1],
              [1,0,1,1],
              [1,1,0,0],
              [1,1,0,0]])

M1 = np.array([1,2,3,4])
M2 = np.array([4,3,5,1])


In [22]:
lam1m2, wm1m2 = m.localAssort(A, (M1, M2), pr=0.5)
lam2m1, wm2m1 = m.localAssort(A, (M2, M1), pr=0.5)
lam1, wm1 = m.localAssort(A, M1, pr=0.5)
lam2, wm2 = m.localAssort(A, M2, pr=0.5)

In [23]:
print(lam1m2)
print(lam2m1)
print(lam1)
print(lam2)

[-0.41919107 -0.42372616 -0.64370433 -0.53292952]
[-0.10838006 -0.05195899  0.05756903 -0.12973948]
[-0.58338747 -0.52485612 -0.70232253 -0.59687624]
[-0.07772359 -0.04110611  0.0518211  -0.11675253]


In [20]:
X = [1,1,1,2,2,2,3,3,4,4]
Y = [2,3,4,1,3,4,1,2,1,2]
pearsonr(X,Y)[0]

-0.5702479338842976

In [21]:
X = [1,1,1,2,2,2,3,3,4,4]
Y = [3,2,1,4,2,1,4,3,4,3]
pearsonr(X,Y)[0]

0.5702479338842976